export function initialWorkspaceState() {
  return {
    activeGraphMapId: "",
    activePaneId: "",
    activeTabId: "welcome",
    auth: null,
    capabilities: [],
    commandPaletteOpen: false,
    currentBlogPost: null,
    currentBlogPostId: "",
    currentMediaAssetId: "",
    currentNodeId: "",
    edges: [],
    feedItems: [],
    history: [],
    lastError: "",
    layout: null,
    layoutDirty: false,
    layoutNodeId: "",
    mediaAssets: [],
    nodes: [],
    online: navigator.onLine,
    queued: 0,
    queueEntries: [],
    rejected: 0,
    setupChecked: false,
    setupError: "",
    setupRequired: false,
    tabChooserOpen: false,
    tabChooserPaneId: "",
    tabDrafts: {},
    tabScrolls: {},
    text: "",
    textDirty: false,
    textSnapshots: {},
  };
}
